#! /usr/bin/env python

# len_removeparticles
# James Mithen
# Remove particles from .xyz file if they have a given symbol e.g.
# 'S', 'N', 'O'.  Note that symbol can be anything but must be a
# single character (input like SNO will be treated as three characters,
# and a particle with any of these symbols will be removed).

import sys
import readwrite

if len(sys.argv) != 4:
    sys.exit("Syntax stripsymbols symbols infile.xyz outfile.xyz")

# symbols can be given as S SNO etc. so can strip multiple symbols by
# running this script only once
strips = list(sys.argv[1])
infile = sys.argv[2]
outfile = sys.argv[3]

# read infile positions and symbols
try:
    fin = open(infile,'r')
except IOError:
    sys.exit("Problem reading file %s" %infile)
positions,symbols = readwrite.rxyz(infile,True)
fin.close()
npar = len(positions)

outstr = ''
np = 0 # number of particles not stripped
for i in range(npar):
    if symbols[i] not in strips:
        outstr = '%s%s %.8f %.8f %.8f\n' %(outstr,symbols[i],
                                           positions[i][0],
                                           positions[i][1],
                                           positions[i][2])
        np = np + 1
outstr = '%d\n\n%s' %(np,outstr)

# write to outfile
fout = open(outfile,'w')
fout.write(outstr)
fout.close()


        



    
