#! /usr/bin/env python

# len_shiftpositive
# James Mithen

# Shift the positions in an XYZ file so that each particle has
# positive x,y,z position.  Then print box dims.

import readwrite
import numpy as np

# make positions positive by at least this amount (we don't want to
# have particles with an x,y or z co-ord closer to the origin than
# _EPS).
_EPS = 0.1

if len(sys.argv) != 3:
    sys.exit("Syntax len_shiftpositive infile.xyz outfile")

infile = sys.argv[1]
outfile = sys.argv[2]

positions, symbols = readwrite.rxyz(infile, True)
npar = len(positions)

# get min in x, y and z directions
minpos = np.min(positions, axis=0)

# offsets to add: we only add something to all positions if min[x/y/z]
# is < 0.
offset = [-1.0*min(0.0, s - _EPS) for s in minpos]

print 'Not yet fully implemented'

